DataDog/datadog-api-client-python

setup.cfg

Pytest-bdd released 4.0.0 yesterday with some breaking changes that are causing the CI to fail. We'll need to investigate these and migrate, but this unblocks the CI for now

pin pytest-bdd

---

tests/conftest.py

- adds a length check step to BDD testing tools, useful when testing list endpoints

Add a length check to BDD tooling

---

setup.py

Updates the version_template to state 2020 - Present

Update version_template to include Present

---

setup.cfg

Update docs link to point to datadoghq.dev

---

CHANGELOG.md

Add changelog for beta 2

---

.azure-pipelines/all.yml
tests/conftest.py
tests/v1/test_scenarios.py
tests/v2/test_scenarios.py

⬆️ 
uses https://github.com/DataDog/dd-trace-py/pull/1741

Add CI tags to tracked spans

---

CHANGELOG.md

Release 1.0.0b4

---

setup.cfg
tests/conftest.py

Fixes compatibility with recently released `ddtrace` lib.

tests: bump ddtrace 0.46.0

---

tests/conftest.py

Followup to #252, this formats the last file in this repo (one thats not generated), using `black`

Format conftest

---

CHANGELOG.md

Release 1.0.0b6

---

.github/workflows/changelog.yaml

Don't run changelog checker until PR is ready for review

---

setup.cfg

Remove nulltype

---

CHANGELOG.md

Changelog for 1.2.0

---

CHANGELOG.md

Changelog for 1.3

---

setup.cfg

tests: unpin ddtrace for better dogfooding

---

CHANGELOG.md

Prepare 1.4 release

---

extract-code-blocks.awk

Fix example extraction for SLO

---

CHANGELOG.md

Changelog for 1.7

---

.github/workflows/test_integration.yml
tests/conftest.py

Sleep after request if needed

---

README.md

Change debug wording

---

docs/README.md

Fix RTD index and sync with top README

---

CHANGELOG.md

Changelog for 1.8

---

.github/release.yml

Add changelog config

---

.github/workflows/prepare_release.yml
.github/workflows/release.yml

This generates the changelog and creates a PR to update our file.

Add a workflow to create the changelog

---

.github/workflows/docs.yml

Remove uncompression step

---

.gitignore
.pre-commit-config.yaml
Makefile
docs/datadog_api_client.rst
docs/datadog_api_client.v1.api.rst
docs/datadog_api_client.v1.model.rst
docs/datadog_api_client.v1.rst
docs/datadog_api_client.v2.api.rst
docs/datadog_api_client.v2.model.rst
docs/datadog_api_client.v2.rst
tox.ini

Commit generated API docs

---

.generator/src/generator/templates/api.j2
src/datadog_api_client/v1/api/key_management_api.py
src/datadog_api_client/v1/api/metrics_api.py
src/datadog_api_client/v1/api/organizations_api.py
src/datadog_api_client/v2/api/auth_n_mappings_api.py
src/datadog_api_client/v2/api/key_management_api.py
src/datadog_api_client/v2/api/logs_api.py
src/datadog_api_client/v2/api/logs_archives_api.py
src/datadog_api_client/v2/api/metrics_api.py
src/datadog_api_client/v2/api/roles_api.py
src/datadog_api_client/v2/api/rum_api.py
src/datadog_api_client/v2/api/security_monitoring_api.py
src/datadog_api_client/v2/api/service_accounts_api.py
src/datadog_api_client/v2/api/users_api.py

Minor docstring fix

---

.generator/src/generator/templates/api_client.j2
.generator/src/generator/templates/base_configuration.j2
.generator/src/generator/templates/model_utils.j2
.generator/src/generator/templates/rest.j2
run-tests.sh
setup.cfg
src/datadog_api_client/api_client.py
src/datadog_api_client/configuration.py
src/datadog_api_client/model_utils.py
src/datadog_api_client/rest.py

This adds some typing information to make sure we can run mypy on the
code base.

Add basic mypy structure

---

setup.cfg
tests/conftest.py

Bump pytest-bdd, remove unused six dep, move skip tags earlier in tests.

Bump pytest-bdd

---

.generator/src/generator/openapi.py
src/datadog_api_client/v1/model/monitor_options.py

Fix type of nullable additionalProperties

---

.generator/src/generator/replacement.json
src/datadog_api_client/v1/api/service_level_objectives_api.py

Renames `list_sl_os` back to `list_slos`.

Fix camel case version of `ListSLOs`

---

.generator/conftest.py
.generator/poetry.lock
.generator/pyproject.toml
.pre-commit-config.yaml

Skip pagination, and fix wrong dependency.

Fix example generation

---

.generator/src/generator/openapi.py
src/datadog_api_client/v1/model/alert_value_widget_definition.py
src/datadog_api_client/v1/model/change_widget_request.py
src/datadog_api_client/v1/model/distribution_widget_request.py
src/datadog_api_client/v1/model/geomap_widget_request.py
src/datadog_api_client/v1/model/heat_map_widget_request.py
src/datadog_api_client/v1/model/host_map_request.py
src/datadog_api_client/v1/model/host_map_widget_definition_requests.py
src/datadog_api_client/v1/model/log_query_definition.py
src/datadog_api_client/v1/model/monitor_group_search_response_counts.py
src/datadog_api_client/v1/model/monitor_search_response_counts.py
src/datadog_api_client/v1/model/query_value_widget_definition.py
src/datadog_api_client/v1/model/query_value_widget_request.py
src/datadog_api_client/v1/model/scatter_plot_request.py
src/datadog_api_client/v1/model/scatter_plot_widget_definition.py
src/datadog_api_client/v1/model/scatter_plot_widget_definition_requests.py
src/datadog_api_client/v1/model/slo_history_metrics.py
src/datadog_api_client/v1/model/slo_history_response_data.py
src/datadog_api_client/v1/model/sunburst_widget_request.py
src/datadog_api_client/v1/model/synthetics_test_request_certificate.py
src/datadog_api_client/v1/model/table_widget_request.py
src/datadog_api_client/v1/model/timeseries_widget_definition.py
src/datadog_api_client/v1/model/timeseries_widget_request.py
src/datadog_api_client/v1/model/toplist_widget_request.py
src/datadog_api_client/v1/model/usage_billable_summary_keys.py
src/datadog_api_client/v2/model/api_key_relationships.py
src/datadog_api_client/v2/model/incident_response_relationships.py
src/datadog_api_client/v2/model/incident_service_relationships.py
src/datadog_api_client/v2/model/incident_team_relationships.py

We can only reference those once.

Remove duplicated lazy imports

---

src/datadog_api_client/api_client.py
tests/conftest.py

Change the tests to enable header matching, and pass all headers in
accepts.

Enable header matching

---

README.md

Document auth

---

.generator/src/generator/templates/rest.j2
src/datadog_api_client/rest.py

Fix compress call

---

.generator/src/generator/formatter.py
src/datadog_api_client/v1/model/synthetics_core_web_vitals.py

We have one attribute in synthetics named cls which breaks some method
calls. Let's add it to the list of keywords.

Add cls to the list of keywords

---

.generator/src/generator/formatter.py
examples/v2/logs/ListLogsGet_2034110533.py

Fix examples requiring tzoffset

---

.github/workflows/approved_status.yml
.github/workflows/docs.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/test_integration.yml

This sets up the action with cache.

Use cache in CI

---

.generator/src/generator/openapi.py
.generator/src/generator/templates/api.j2
src/datadog_api_client/v2/api/audit_api.py
src/datadog_api_client/v2/api/incidents_api.py
src/datadog_api_client/v2/api/logs_api.py
src/datadog_api_client/v2/api/processes_api.py
src/datadog_api_client/v2/api/rum_api.py
src/datadog_api_client/v2/api/security_monitoring_api.py

Fill up for the typing arguments as we did for regular APIs.

Add typing information to pagination methods

---

.github/workflows/prepare_release.yml

Automatically calculate next version

---

.generator/src/generator/templates/rest.j2
src/datadog_api_client/rest.py

Support proxy in async client

---

README.md

Document proxy usage

---

.generator/src/generator/templates/api_client.j2
.generator/src/generator/templates/model_utils.j2
.generator/src/generator/templates/rest.j2
src/datadog_api_client/api_client.py
src/datadog_api_client/model_utils.py
src/datadog_api_client/rest.py

Make a refurb run on the code base.

Minor cleanups

---

docs/requirements.txt

Looks like 6.1.x might have introduced a regression. Testing 6.0.0

Pin sphinx

---

.github/workflows/docs.yml
docs/requirements.txt
tox.ini

Unpin sphinx

---

.github/workflows/docs.yml
.github/workflows/prepare_release.yml
.github/workflows/release.yml
.github/workflows/stale.yml

We need latest to remove some warnings.

Update github-script action

---

setup.cfg

Pin urllib

---

tests/conftest.py

1.13 changes the location of the URL, let's handle it.

Handle new ddtrace writer

---

setup.cfg

Until 1.14 is out let's keep it at 1.12.

Pin ddtrace

---

.github/workflows/prepare_release.yml
RELEASING.md

Fix release calculation and notes

---

.generator/src/generator/formatter.py

Remove warnings in example generation

---

.generator/src/generator/templates/configuration.j2
src/datadog_api_client/configuration.py

Add docs for retry parameters

---

tests/test_async.py

SSIA, handle new edge validation

Change fake auth keys to use valid format

---

TESTING.md

Fixes #1711 about a typo in TESTING.md where "behaviro" should be "behavior"
What inspired you to submit this pull request?
I looked at the TESTING.md and saw it.
N/A

Fix "behavior" typo in TESTING.md

---

.generator/conftest.py
.generator/src/generator/openapi.py

update explicit x-merge-overrides handling to generic extensions

---

.generator/src/generator/openapi.py

Fixes missing imports when a oneOf is in a nested array and its variants aren't imported.

Fix nested array oneOf imports

---

.generator/src/generator/templates/example.j2
examples/v2/security-monitoring/GetHistoricalJob.py
examples/v2/security-monitoring/ListHistoricalJobs.py

https://github.com/DataDog/datadog-api-client-go/pull/2778

sort enabled ops

---

tests/conftest.py
tests/v2/features/on-call.feature

Mostly based on [the change](https://github.com/DataDog/datadog-api-client-python/pull/2517/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R508) recommended by @skarimo .

Use the client to deserialize the parameter

---

tests/v2/features/on-call.feature

Restore skip-python (so we can remove it in the main PR).
