DataDog/datadog-api-client-python

tests/conftest.py
- adds a handling for BDD "given" clauses that enable unstable operations
- this is necessary to support BDD testing for unstable endpoints being added for incident management
=> add handling in bdd runner for unstable operations

RELEASING.md
This PR adds a RELEASING.md file for this project. This is mostly taken from the datadogpy version and is what was followed for releasing beta1.
=> Add release doc

.github/workflows/release.yml
Adds a github action workflow for creating and uploading a package to pypi. This essentially translates the same RELEASING.md file we use now as a github action. 
The release workflow will be to create a "release" on github, and have this automatically triggered to build and push the packaged wheel to pypi. 
Once this is tested with one release, I can update the RELEASE.md file
=> Add job for uploading the package

.github/workflows/release.yml
ddev expects the config to look like:
[pypi]
user = <username>
pass = <password>
Source - https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/tooling/commands/release/upload.py#L35
I previously set this as `token` instead of `pass`
=> Set ddev config pypi pass

CHANGELOG.md
Preps the 1.0.0b3 release, following the steps from RELEASING.md
=> Release 1.0.0b3

CHANGELOG.md
=> Release 1.0.0b7

CHANGELOG.md
* [Added] Add `reflow_type` property to dashboard object. See [#372](https://github.com/DataDog/datadog-api-client-python/pull/372).
* [Added] Add security track and formulas and functions support for geomap dashboard widget. See [#370](https://github.com/DataDog/datadog-api-client-python/pull/370).
* [Added] Generate intake endpoints. See [#367](https://github.com/DataDog/datadog-api-client-python/pull/367).
* [Added] Add endpoint for listing all downtimes for the specified monitor. See [#361](https://github.com/DataDog/datadog-api-client-python/pull/361).
* [Added] Add `modified_at` attribute to user response v2 schema. See [#352](https://github.com/DataDog/datadog-api-client-python/pull/352).
* [Added] Add default environment loading in clients. See …
=> Release 1.0.0b8

tests/conftest.py
We match attributes using its json path + the json response object, hence no need to convert it to snake case.
=> Don't convert paths to snake case

.generator/templates/model_utils.mustache, src/datadog_api_client/v1/model_utils.py, src/datadog_api_client/v2/model_utils.py, tests/test_deserialization.py
The discarding when coming from the API is not very useful, let's try to
store raw data.
=> Store unknown model properties in `_data_store` map

.github/workflows/publish.yml
Adds `sdist` target.
See also https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
Closes #858
=> Publish sdist

.github/workflows/test_integration.yml
Make it simpler to use `datadog-ci`: use new standalone binary instead of setting up node and installing `datadog-ci` with `npm`
=> Use standalone binary for `datadog-ci` instead of `npm`

.github/workflows/test.yml, setup.cfg
3.6 is EOL, let's make 3.7 the minimum.
=> Bump minimum python

setup.cfg, tests/conftest.py
It's pretty slow and we don't need to patch all modules when freezing
time, as we explicitly call time functions.
=> Remove freezegun usage

.github/workflows/test_integration.yml
Remove `datadog-ci git-metadata upload` that sends git metadata as it's not required by #source-code-integration anymore.
=> Remove datadog-ci git-metadata upload

.github/workflows/test_integration.yml, setup.cfg, tests/conftest.py
---
Trace
https://app.datadoghq.com/ci/test-commit/github.com%2FDataDog%2Fdatadog-api-client-python/datadog-api-client-python/jirikuncar%2FITL-788%2Fpytest-bdd/bd646a13d8d3ccaa3e4a896340b275bbe36a6c51?query=env%3Aprod%20%40git.repository.id%3A%22github.com%2FDataDog%2Fdatadog-api-client-python%22%20%40test.service%3Adatadog-api-client-python%20%40git.branch%3A%22jirikuncar%2FITL-788%2Fpytest-bdd%22%20%40git.commit.sha%3Abd646a13d8d3ccaa3e4a896340b275bbe36a6c51&currentTab=trace&env=prod&index=citest&spanID=2961140448467777036&trace=AQAAAYEkvBJIaqI2jwAAAABBWUVrdkJKSUFBQWZLaWZVWlVqNlZLTGY&start=1651586739987&end=1654178739987&paused=false
=> tests: use upstream pytest-bdd traces

.generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py, tests/test_serialization.py
We were basing the creation on the presence of optional parameters, so
it failed and got an unparsed object.
=> Fix oneOf primitive objects creation

setup.cfg
6.1.0 introduces a breaking change that changes the order of pytest hooks and breaks our tests.
=> pin pytest-bdd version to 6.0.1

tests/conftest.py
Adds a check in the tests to support when the operation tag and undo operation tag differ. This came up when trying to move the CreateServiceAccount endpoint from the Users tag to the Service Accounts tag. The tests currently try to use the `ServiceAccountsApi.disable_user` operation, when it needs to find the `UsersApi.disable_user` op.
=> Support differing operation tag and undo tag

.generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py
Remove that weird class method that always bothered me.
=> Small model cleanup

setup.cfg
onecache 0.4.1 is not building properly, seems like the newer version is not python 3.11 compatible but the older one was.
aiosonic 0.16.0 depends on onecache 0.4.1, so instead pin aiosonic to the previous version.
=> Pin aiosonic due to issue with its dependency onecache 0.4.1

.generator/src/generator/templates/rest.j2, src/datadog_api_client/rest.py
This adds support for retry in the async client.
=> Support retry in async client

.generator/src/generator/templates/rest.j2, src/datadog_api_client/rest.py
The current datadog api client fails to pass ssl_verify argument to the AsyncApiClient which will result in 
`self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)` 
Linked Issue: https://github.com/DataDog/datadog-api-client-python/issues/1654
=>  Pass SSL configuration arguments to Async Api Client

setup.cfg, setup.py
Avoid panics such as:
```
TypeError: parse_fetch_on_shallow() got an unexpected keyword argument 'config'
```
=> Pass all keyword/ arguments to avoid panics with `setuptools_scm` > 8

tests/conftest.py
This doesn't work in 2.x and we use PYTEST_ADDOPTS anyway.
=> Remove tracer custom setup

setup.cfg
We need it for the `Self` definition if you're not on python 3.11.
Fixes #1727
=> Add minimal typing_extensions version

.generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py
=> Make validation target type a union of int and float

setup.cfg
ddtrace is incompatible with pytest 8, pin this until a fix is released.
=> Pin pytest below 8.0.0

tests/conftest.py
Follow up to https://github.com/DataDog/datadog-api-client-python/pull/1901 because I misspelled the name of the step. It's defined here:
https://github.com/DataDog/datadog-api-client-python/blob/fe7a9a63e7470c1b0e62b0cc8a61cb0ce0653c2a/.generator/conftest.py#L541-L543
=> Fix step name

.generator/src/generator/openapi.py, .generator/src/generator/templates/model_generic.j2, .generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py, src/datadog_api_client/v1/model/notebook_cell_create_request.py, src/datadog_api_client/v1/model/slo_time_slice_spec.py, src/datadog_api_client/v2/model/bulk_mute_findings_request_attributes.py, src/datadog_api_client/v2/model/bulk_mute_findings_request_properties.py, src/datadog_api_client/v2/model/cloud_configuration_compliance_rule_options.py, src/datadog_api_client/v2/model/downtime_monitor_identifier_id.py, src/datadog_api_client/v2/model/downtime_monitor_identifier_tags.py, src/datadog_api_client/v2/model/downtime_schedule_one_time_create_update_request.py, src/datadog_api_client/v2/model/downtime_schedule_recurrence_create_update_request.py, src/datadog_api_client/v2/model/downtime_schedule_recurrences_update_request.py, src/datadog_api_client/v2/model/finding_mute.py, src/datadog_api_client/v2/model/finding_rule.py, src/datadog_api_client/v2/model/list_findings_meta.py, src/datadog_api_client/v2/model/list_findings_page.py, src/datadog_api_client/v2/model/security_monitoring_rule_query_payload_data.py, src/datadog_api_client/v2/model/security_monitoring_signal_attributes.py, src/datadog_api_client/v2/model/workflow_instance_create_response.py, src/datadog_api_client/v2/model/workflow_instance_create_response_data.py, src/datadog_api_client/v2/model/workflow_instance_list_item.py, src/datadog_api_client/v2/model/workflow_list_instances_response.py, src/datadog_api_client/v2/model/workflow_list_instances_response_meta.py, src/datadog_api_client/v2/model/workflow_list_instances_response_meta_page.py, src/datadog_api_client/v2/model/worklflow_get_instance_response.py, src/datadog_api_client/v2/model/worklflow_get_instance_response_data.py, src/datadog_api_client/v2/model/worklflow_get_instance_response_data_attributes.py
Currently, there is some conflicting behavior across multiple code paths. Some code path assumes additionalProperties is false by default where others, it is enabled. For example see: 
https://github.com/DataDog/datadog-api-client-python/blob/master/.generator/src/generator/templates/model_utils.j2#L132
and 
https://github.com/DataDog/datadog-api-client-python/blob/master/.generator/src/generator/templates/model_utils.j2#L400
To make sure behavior is uniform, lets enabled additionalProperties by default.
=> Enable additionalProperties by default

.generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py
Handle nested oneOf models during serialization.
Fixes: https://github.com/DataDog/datadog-api-client-python/pull/2125
=> Handle nested oneOfs during serialization

.generator/src/generator/templates/api_client.j2, .generator/src/generator/templates/rest.j2, src/datadog_api_client/api_client.py, src/datadog_api_client/rest.py, tests/test_async.py
Fixes https://github.com/DataDog/datadog-api-client-python/issues/2139
=> Fix crash when closing an async client.

.generator/src/generator/templates/model_utils.j2, .pre-commit-config.yaml, src/datadog_api_client/model_utils.py
Strings should only be deserialized into UUIDs if the type is explicitly UUID - otherwise, random hashes that aren't uuids can be converted unintentionally. The only time both str and UUID is valid for a type is for arbitrary type fields, so this only applies to arbitrary objects and additionalProperties.
Also pins the Sphinx version in pre-commit to stabilize the `.rst` doc files. (7.4.0 has a slightly different format to ^8.0.0)
=> Stop strings in arbitrary type fields from automatically converting to UUID

.generator/src/generator/templates/model_utils.j2, src/datadog_api_client/model_utils.py
Fixes the typing on `__new__` and makes constructors typing behave properly.
before:
after:
=> fix `__new__` typing for OpenApiModel

.github/workflows/test.yml
setuptools now enforces naming restrictions in `setup.cfg`
=> pin setuptools

tests/test_async.py, tests/test_thread.py
`test_async` has been flaking since headers are case insensitive — `test_thread` does the same type of check so we should make the update in that test as well
=> fix flaky tests due to header casing

tests/test_async.py
If no APP key is passed at all, Metrics API has started to return a 401 instead of a 403
=> add fake app key

.github/workflows/test.yml
Failing fast makes it impossible to determine if the issue is specific to one job in the matrix or not, as we would never get the results from the others to compare.
=> Do not cancel concurrent CI matrix jobs

.github/workflows/reusable-ci.yml, .github/workflows/reusable-examples.yml, .github/workflows/reusable-integration-test.yml, .github/workflows/reusable-pre-commit.yml, .github/workflows/reusable-python-test.yml, .github/workflows/test.yml
This PR implements the CI workflow modernization for the **python** client by converting all CI jobs to reusable workflows. This aligns the python client with the established pattern from the Go clients ([see PR](https://github.com/DataDog/datadog-api-client-go/pull/3343)) and enables centralized CI management for the datadog-api-spec repository.
This work enables:
- **Complete CI reusability**: The datadog-api-spec repo can now call a single reusable workflow and get the full CI pipeline (pre-commit, unit tests, examples, integration tests)
- **MergeQueue compatibility**: Centralizing all CI jobs in reusable workflows is essential for enabling the MergeQueue functionality
- **Consistent local development**: The local `test.yml` maintains the familiar individual job structure while …
=> Convert python testing workflow to reusable workflow
